'use client';

import { useCallback, useState } from "react";

type ButtonType = "be" | "md" | "bb" | null

export function ButtonList() {
    const [selected, setSelected] = useState<ButtonType>(null)

    const toggle = useCallback((type: ButtonType) => {
        setSelected(selected => selected === type ? null : type)
    }, [])

    const close = useCallback(() => {
        setSelected(null)
    }, [])

    return (
        <>
            {selected === "be" ? <BECard close={close} /> : <BEButton toggle={toggle} />}
            {selected === "md" ? <MDCard close={close} /> : <MDButton toggle={toggle} />}
            {selected === "bb" ? <BBCard close={close} /> : <BBButton toggle={toggle} />}
        </>
    )
}

function BEButton({ toggle }: { toggle: (type: ButtonType) => void }) {
    return (
        <button className="btn btn-be" onClick={() => toggle("be")}>
            BlockEstate
        </button>
    );
}

function MDButton({ toggle }: { toggle: (type: ButtonType) => void }) {
    return (
        <button className="btn btn-md" onClick={() => toggle("md")}>
            Medjool Defi
        </button>
    );
}

function BBButton({ toggle }: { toggle: (type: ButtonType) => void }) {
    return (
        <button className="btn btn-bb" onClick={() => toggle("bb")}>
            Biera Brewery
        </button>
    );
}

function BECard({ close }: { close: () => void }) {
    return (
        <div className="card card-be">
            <h2 className="card-title hover:cursor-pointer" onClick={close}>
                BlockEstate
            </h2>
            <p>
                BlockEstate is a tokenized real estate investment fund, which enables its community to actively participate
                in the decision making progress, while also benefiting from the profits generated by real world assets.
            </p>
            <div className="card-footer">
                <a href="https://blockestate.finance" target="_blank" rel="norefferer">Website</a>
                &nbsp;-&nbsp;
                <a href="https://blockestate.finance/litepaper" target="_blank" rel="norefferer">LitePaper</a>
                &nbsp;-&nbsp;
                <a href="https://blockestate.finance/roadmap" target="_blank" rel="norefferer">Roadmap</a>
            </div>
        </div>
    )
}

function MDCard({ close }: { close: () => void }) {
    return (
        <div className="card card-md">
            <h2 className="card-title hover:cursor-pointer" onClick={close}>
                Medjool Defi
            </h2>
            <p>
                To be announced
            </p>
        </div>
    )
}

function BBCard({ close }: { close: () => void }) {
    return (
        <div className="card card-bb">
            <h2 className="card-title hover:cursor-pointer" onClick={close}>
                Biera Brewery
            </h2>
            <p>
                To be announced
            </p>
        </div>
    )
}
